### ISSUE TITLE
Easy access to report/logs of WorkChains and CalcJobs

### ISSUE THREAD

**Issue by bosonie** [giovannipizzi/aiida-node-shell#3]
It would be nice to have a command that returns the report/logs of a WorkChain/CalcJob when the corresponding WorkChainNode/CalcJobNode is loaded in the shell.
This command should be available only when a WorkChainNode/CalcJobNode is loaded, and not when a Data node is loaded.

**Comment by giovannipizzi** [comment]
Fixed in #4
